version: "3.7"

services:
  varvar_vpn_develop:
    cap_add:
      - SYS_PTRACE
    build:
     context: ./docker/develop/
     dockerfile: /home/slave/Documents/VarvarVPN/docker/develop/Dockerfile
    volumes:
      - nfsmount:/home/varvarvpn/ 
      - ~/.ssh:/home/varvarvpn/.ssh
    ports:
      - "8080:80"
      - "8433:433"
  
  varvar_vpn_release:
    build:
      context: ./docker/release
      dockerfile: /home/slave/Documents/VarvarVPN/docker/release/Dockerfile

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: bind
      device: /home/slave/Documents/VarvarVPN
networks:
  default:
    external:
      name: bridge-default

